<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Push notifications: the devices to send to, and who wants what.
 *
 * ---- written by hand, like the last one -------------------------------------
 *
 * Same reason as Version20260805214413: doctrine:migrations:diff cannot see the
 * DBAL-written tables or the partial indexes, so it proposes to drop them
 * alongside anything useful it generates. Only the additions are here.
 *
 * ---- why token is TEXT with its own unique index ----------------------------
 *
 * An FCM registration token identifies an app install, not a person. When a
 * second account signs in on the same phone, Google hands back the same token,
 * and the row has to move to the new owner rather than duplicate — otherwise
 * the previous owner keeps receiving the new one's notifications. That upsert
 * needs the unique constraint to be enforced by the database, because two
 * sign-ins racing on the same device is a real sequence, not a theoretical one.
 *
 * Google publishes no maximum length for a token and has changed it before, so
 * the column is unbounded. Postgres indexes TEXT the same as VARCHAR.
 */
final class Version20260807120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Device tokens for push, and per-account push preferences.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE device_tokens (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            token TEXT NOT NULL,
            platform VARCHAR(16) NOT NULL,
            locale VARCHAR(5) DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id),
            CONSTRAINT fk_device_token_user FOREIGN KEY (user_id)
                REFERENCES users (id) ON DELETE CASCADE
        )');

        $this->addSql('CREATE UNIQUE INDEX uniq_device_token ON device_tokens (token)');
        $this->addSql('CREATE INDEX idx_device_token_user ON device_tokens (user_id)');

        // The digest sweeps by staleness, never by user, so this one is for the
        // pruner rather than for sending.
        $this->addSql('CREATE INDEX idx_device_token_stale ON device_tokens (last_seen_at)');

        /*
         * '{}' rather than NULL: absent means "wants everything", and the code
         * reads a missing key as true. A nullable column would make "never
         * opened settings" and "switched everything off" the same shape at the
         * database level, which is the bug that ships push to people who opted
         * out.
         */
        $this->addSql("ALTER TABLE users ADD push_prefs JSONB DEFAULT '{}' NOT NULL");

        /*
         * When this account was last sent a digest.
         *
         * The digest command runs hourly and sends to whoever is at 9am local,
         * which is correct exactly as long as it runs once per hour. Re-running
         * it by hand, a cron that fires twice, or a zone crossing 9am twice on
         * a DST fall-back would all send the same person the same digest again.
         * This column is what makes the command safe to run as often as anyone
         * likes.
         */
        $this->addSql('ALTER TABLE users ADD push_digest_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS device_tokens');
        $this->addSql('ALTER TABLE users DROP COLUMN IF EXISTS push_prefs');
        $this->addSql('ALTER TABLE users DROP COLUMN IF EXISTS push_digest_at');
    }
}
