<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Feedback: a report someone filed, and the screenshots on it.
 *
 * ---- written by hand on purpose ---------------------------------------------
 *
 * doctrine:migrations:diff produced this plus a demolition: it wanted to drop
 * work_tag, work_related and seven partial indexes. None of those are wrong —
 * they are simply invisible to it. The two tables have no entities (they are
 * written with DBAL for speed) and the indexes are partial, with WHERE clauses
 * the ORM's schema model cannot express. Everything the diff cannot see, it
 * proposes to delete.
 *
 * So only the two new tables survive here. Worth remembering the next time a
 * diff is generated in this project: read it before running it, because the
 * useful half arrives mixed with the destruction of the hand-built half.
 *
 * ---- the shape ---------------------------------------------------------------
 *
 * Images are their own table rather than a json column on the report, because
 * they are the only part of this that costs disk and they have to be reclaimable
 * on their own — see purged_at, and app:feedback:purge.
 */
final class Version20260805214413 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Feedback reports and their screenshots';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE feedback (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            category VARCHAR(16) NOT NULL,
            status VARCHAR(16) NOT NULL,
            body TEXT NOT NULL,
            note TEXT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id),
            CONSTRAINT fk_feedback_user FOREIGN KEY (user_id)
                REFERENCES users (id) ON DELETE CASCADE
        )');

        // The admin queue reads by status, newest first.
        $this->addSql('CREATE INDEX idx_feedback_status ON feedback (status, created_at)');

        // And a person reads their own, newest first.
        $this->addSql('CREATE INDEX idx_feedback_user ON feedback (user_id, created_at)');

        $this->addSql('CREATE TABLE feedback_image (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            feedback_id INT NOT NULL,
            path VARCHAR(255) NOT NULL,
            position INT NOT NULL,
            bytes INT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            purged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id),
            CONSTRAINT fk_feedback_image_feedback FOREIGN KEY (feedback_id)
                REFERENCES feedback (id) ON DELETE CASCADE
        )');

        $this->addSql('CREATE INDEX idx_feedback_image_feedback ON feedback_image (feedback_id, position)');

        // Partial: the purge only ever asks for the ones still holding a file.
        $this->addSql('CREATE INDEX idx_feedback_image_purge
            ON feedback_image (created_at) WHERE purged_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS feedback_image');
        $this->addSql('DROP TABLE IF EXISTS feedback');
    }
}
