<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The whole schema, in one migration.
 *
 * This replaces the thirteen migrations that built the catalog incrementally —
 * renames, backfills, a couple of corrections. None of that history is useful
 * to a database that has never been created, and a single baseline is far
 * easier to read and to trust.
 *
 * It is written from a `pg_dump --schema-only` of the schema those migrations
 * produced, not generated by `doctrine:migrations:diff`, because a diff only
 * knows what the ORM knows. It would have quietly dropped:
 *
 *   - the pg_trgm extension, and with it every fuzzy search in the app
 *   - `works.search_vector`, a generated tsvector column no entity owns
 *   - the GIN/trigram index types (a diff writes them as plain btree)
 *   - the partial indexes on the crawl queue
 *   - `tmdb_movie_ids` entirely, which is excluded from schema comparison
 *   - the trigger and function that keep works.external_score in step
 *
 * Order matters in one place: the extension is created first, because the
 * trigram indexes below refer to its operator classes.
 */
final class Version20260731000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baseline: complete catalog schema, search indexes, crawl queue and rating trigger';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public');

        $this->addSql(<<<'SQL'
CREATE FUNCTION refresh_work_primary_score() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
            DECLARE target_id integer;
            BEGIN
                target_id := COALESCE(NEW.work_id, OLD.work_id);
                UPDATE works w SET external_score = (
                    SELECT ROUND((r.rating / NULLIF(r.scale, 0) * 100)::numeric, 1)
                    FROM work_ratings r
                    WHERE r.work_id = target_id
                    ORDER BY CASE r.source
                        WHEN 'imdb' THEN 1
                        WHEN 'tmdb' THEN 2
                        WHEN 'metacritic' THEN 3
                        ELSE 4
                    END
                    LIMIT 1
                )
                WHERE w.id = target_id;
                RETURN NULL;
            END
        $$
SQL);

        $this->addSql('CREATE TABLE access_tokens (
    id integer NOT NULL,
    token character varying(128) NOT NULL,
    refresh_token character varying(128) NOT NULL,
    expires_at timestamp(0) without time zone NOT NULL,
    refresh_token_expires_at timestamp(0) without time zone NOT NULL,
    ip_address character varying(45) DEFAULT NULL::character varying,
    user_agent character varying(255) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    deleted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    user_id integer NOT NULL
)');

        $this->addSql('ALTER TABLE access_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME access_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE credits (
    id integer NOT NULL,
    work_id integer NOT NULL,
    person_id integer NOT NULL,
    role character varying(24) NOT NULL,
    character_name character varying(255) DEFAULT \'\'::character varying NOT NULL,
    "position" smallint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_credit_role CHECK (((role)::text = ANY ((ARRAY[\'cast\'::character varying, \'director\'::character varying, \'writer\'::character varying, \'creator\'::character varying, \'developer\'::character varying, \'publisher\'::character varying, \'author\'::character varying])::text[])))
)');

        $this->addSql('ALTER TABLE credits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME credits_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE entries (
    id integer NOT NULL,
    status character varying(16) NOT NULL,
    rating numeric(2,1) DEFAULT NULL::numeric,
    progress json,
    updated_at timestamp(0) without time zone NOT NULL,
    user_id integer NOT NULL,
    work_id integer CONSTRAINT entries_item_id_not_null NOT NULL,
    CONSTRAINT chk_entry_rating CHECK (((rating IS NULL) OR ((rating >= 0.5) AND (rating <= (5)::numeric)))),
    CONSTRAINT chk_entry_status CHECK (((status)::text = ANY ((ARRAY[\'wishlist\'::character varying, \'active\'::character varying, \'done\'::character varying, \'dropped\'::character varying])::text[])))
)');

        $this->addSql('ALTER TABLE entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE episodes (
    id integer NOT NULL,
    number integer NOT NULL,
    title character varying(255) DEFAULT NULL::character varying,
    runtime integer,
    air_date date,
    overview text,
    season_id integer NOT NULL
)');

        $this->addSql('ALTER TABLE episodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME episodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE external_ids (
    id integer NOT NULL,
    work_id integer NOT NULL,
    source character varying(24) NOT NULL,
    external_id character varying(64) NOT NULL
)');

        $this->addSql('ALTER TABLE external_ids ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME external_ids_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE follows (
    id integer NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    follower_id integer NOT NULL,
    followed_id integer NOT NULL,
    CONSTRAINT chk_follow_not_self CHECK ((follower_id <> followed_id))
)');

        $this->addSql('ALTER TABLE follows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME follows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE genres (
    id integer NOT NULL,
    slug character varying(80) NOT NULL,
    name character varying(80) NOT NULL
)');

        $this->addSql('ALTER TABLE genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME genres_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE seen_marks (
    id integer CONSTRAINT item_seens_id_not_null NOT NULL,
    seen_at timestamp(0) without time zone CONSTRAINT item_seens_seen_at_not_null NOT NULL,
    user_id integer CONSTRAINT item_seens_user_id_not_null NOT NULL,
    work_id integer CONSTRAINT item_seens_item_id_not_null NOT NULL
)');

        $this->addSql('ALTER TABLE seen_marks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME item_seens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE people (
    id integer NOT NULL,
    slug character varying(200) NOT NULL,
    name character varying(180) NOT NULL,
    photo character varying(500) DEFAULT NULL::character varying,
    external_id character varying(64) DEFAULT NULL::character varying
)');

        $this->addSql('ALTER TABLE people ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME people_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE review_versions (
    id integer NOT NULL,
    rating numeric(2,1) NOT NULL,
    body text NOT NULL,
    edited_at timestamp(0) without time zone NOT NULL,
    review_id integer NOT NULL,
    CONSTRAINT chk_review_version_rating CHECK (((rating >= 0.5) AND (rating <= (5)::numeric)))
)');

        $this->addSql('ALTER TABLE review_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME review_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE reviews (
    id integer NOT NULL,
    rating numeric(2,1) NOT NULL,
    body text NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    user_id integer NOT NULL,
    work_id integer CONSTRAINT reviews_item_id_not_null NOT NULL,
    CONSTRAINT chk_review_rating CHECK (((rating >= 0.5) AND (rating <= (5)::numeric)))
)');

        $this->addSql('ALTER TABLE reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE search_terms (
    term character varying(80) NOT NULL,
    uses integer DEFAULT 1 NOT NULL
)');

        $this->addSql('CREATE TABLE seasons (
    id integer NOT NULL,
    number integer NOT NULL,
    title character varying(255) DEFAULT NULL::character varying,
    overview text,
    poster character varying(500) DEFAULT NULL::character varying,
    work_id integer CONSTRAINT seasons_item_id_not_null NOT NULL
)');

        $this->addSql('ALTER TABLE seasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME seasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE tmdb_movie_ids (
    tmdb_id bigint NOT NULL,
    popularity double precision DEFAULT 0 NOT NULL,
    exported_on date NOT NULL,
    release_year smallint,
    crawled_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
)');

        $this->addSql('CREATE TABLE users (
    id integer NOT NULL,
    username character varying(180) NOT NULL,
    roles json NOT NULL,
    password character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    tagline character varying(255) DEFAULT NULL::character varying,
    bio text,
    location character varying(120) DEFAULT NULL::character varying,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    deleted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    seen_up_to timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
)');

        $this->addSql('ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE work_genre (
    work_id integer NOT NULL,
    genre_id integer NOT NULL
)');

        $this->addSql('CREATE TABLE work_ratings (
    id integer NOT NULL,
    work_id integer NOT NULL,
    source character varying(16) NOT NULL,
    rating numeric(5,2) NOT NULL,
    scale smallint DEFAULT 10 NOT NULL,
    votes integer,
    updated_at timestamp(0) without time zone NOT NULL,
    CONSTRAINT chk_work_rating_range CHECK (((rating >= (0)::numeric) AND (rating <= (scale)::numeric))),
    CONSTRAINT chk_work_rating_source CHECK (((source)::text = ANY ((ARRAY[\'imdb\'::character varying, \'tmdb\'::character varying, \'metacritic\'::character varying, \'steam\'::character varying])::text[])))
)');

        $this->addSql('ALTER TABLE work_ratings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME work_ratings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('CREATE TABLE works (
    id integer CONSTRAINT items_id_not_null NOT NULL,
    type character varying(16) CONSTRAINT items_type_not_null NOT NULL,
    slug character varying(180) CONSTRAINT items_slug_not_null NOT NULL,
    title character varying(255) CONSTRAINT items_title_not_null NOT NULL,
    year integer,
    tagline character varying(500) DEFAULT NULL::character varying,
    overview text,
    poster character varying(500) DEFAULT NULL::character varying,
    backdrop character varying(500) DEFAULT NULL::character varying,
    trailer jsonb,
    external_score double precision,
    source jsonb,
    extra jsonb CONSTRAINT items_details_not_null NOT NULL,
    added_at timestamp(0) without time zone CONSTRAINT items_added_at_not_null NOT NULL,
    release_date date,
    runtime_minutes integer,
    certification character varying(16) DEFAULT NULL::character varying,
    original_language character varying(8) DEFAULT NULL::character varying,
    original_title character varying(255) DEFAULT NULL::character varying,
    vote_count integer,
    popularity double precision,
    page_count integer,
    publisher character varying(180) DEFAULT NULL::character varying,
    search_vector tsvector GENERATED ALWAYS AS ((((setweight(to_tsvector(\'simple\'::regconfig, (COALESCE(title, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'simple\'::regconfig, (COALESCE(original_title, \'\'::character varying))::text), \'B\'::"char")) || setweight(to_tsvector(\'simple\'::regconfig, (COALESCE(tagline, \'\'::character varying))::text), \'C\'::"char")) || setweight(to_tsvector(\'simple\'::regconfig, COALESCE(overview, \'\'::text)), \'D\'::"char"))) STORED,
    CONSTRAINT chk_work_type CHECK (((type)::text = ANY ((ARRAY[\'movie\'::character varying, \'series\'::character varying, \'game\'::character varying, \'book\'::character varying])::text[])))
)');

        $this->addSql('ALTER TABLE works ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME works_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)');

        $this->addSql('ALTER TABLE ONLY access_tokens
    ADD CONSTRAINT access_tokens_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY credits
    ADD CONSTRAINT credits_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY entries
    ADD CONSTRAINT entries_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY episodes
    ADD CONSTRAINT episodes_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY external_ids
    ADD CONSTRAINT external_ids_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY follows
    ADD CONSTRAINT follows_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY people
    ADD CONSTRAINT people_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY review_versions
    ADD CONSTRAINT review_versions_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY search_terms
    ADD CONSTRAINT search_terms_pkey PRIMARY KEY (term)');

        $this->addSql('ALTER TABLE ONLY seasons
    ADD CONSTRAINT seasons_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY seen_marks
    ADD CONSTRAINT seen_marks_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY tmdb_movie_ids
    ADD CONSTRAINT tmdb_movie_ids_pkey PRIMARY KEY (tmdb_id)');

        $this->addSql('ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY work_genre
    ADD CONSTRAINT work_genre_pkey PRIMARY KEY (work_id, genre_id)');

        $this->addSql('ALTER TABLE ONLY work_ratings
    ADD CONSTRAINT work_ratings_pkey PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE ONLY works
    ADD CONSTRAINT works_pkey PRIMARY KEY (id)');

        $this->addSql('CREATE INDEX idx_2df8b3c5a76ed395 ON entries USING btree (user_id)');

        $this->addSql('CREATE INDEX idx_2df8b3c5bb3453db ON entries USING btree (work_id)');

        $this->addSql('CREATE INDEX idx_3a9ec9d93e2e969b ON review_versions USING btree (review_id)');

        $this->addSql('CREATE INDEX idx_4b638a73ac24f853 ON follows USING btree (follower_id)');

        $this->addSql('CREATE INDEX idx_4b638a73d956f010 ON follows USING btree (followed_id)');

        $this->addSql('CREATE INDEX idx_6970eb0fa76ed395 ON reviews USING btree (user_id)');

        $this->addSql('CREATE INDEX idx_6970eb0fbb3453db ON reviews USING btree (work_id)');

        $this->addSql('CREATE INDEX idx_7dd55edd4ec001d1 ON episodes USING btree (season_id)');

        $this->addSql('CREATE INDEX idx_ac12bc0da76ed395 ON seen_marks USING btree (user_id)');

        $this->addSql('CREATE INDEX idx_ac12bc0dbb3453db ON seen_marks USING btree (work_id)');

        $this->addSql('CREATE INDEX idx_access_token_user ON access_tokens USING btree (user_id)');

        $this->addSql('CREATE INDEX idx_b4f4301cbb3453db ON seasons USING btree (work_id)');

        $this->addSql('CREATE INDEX idx_credit_person ON credits USING btree (person_id, role)');

        $this->addSql('CREATE INDEX idx_credit_work_role ON credits USING btree (work_id, role, "position")');

        $this->addSql('CREATE INDEX idx_entry_updated ON entries USING btree (updated_at)');

        $this->addSql('CREATE INDEX idx_external_id_work ON external_ids USING btree (work_id)');

        $this->addSql('CREATE INDEX idx_person_name_trgm ON people USING gin (name gin_trgm_ops)');

        $this->addSql('CREATE INDEX idx_review_version_edited ON review_versions USING btree (review_id, edited_at)');

        $this->addSql('CREATE INDEX idx_search_term_trgm ON search_terms USING gin (term gin_trgm_ops)');

        $this->addSql('CREATE INDEX idx_search_term_uses ON search_terms USING btree (uses DESC)');

        $this->addSql('CREATE INDEX idx_tmdb_export_popularity ON tmdb_movie_ids USING btree (popularity DESC NULLS LAST)');

        $this->addSql('CREATE INDEX idx_tmdb_export_todo ON tmdb_movie_ids USING btree (popularity, tmdb_id) WHERE (crawled_at IS NULL)');

        $this->addSql('CREATE INDEX idx_tmdb_export_todo_year ON tmdb_movie_ids USING btree (release_year, popularity) WHERE (crawled_at IS NULL)');

        $this->addSql('CREATE INDEX idx_tmdb_export_year ON tmdb_movie_ids USING btree (release_year, popularity DESC NULLS LAST)');

        $this->addSql('CREATE INDEX idx_work_added_at ON works USING btree (added_at DESC)');

        $this->addSql('CREATE INDEX idx_work_genre_genre ON work_genre USING btree (genre_id, work_id)');

        $this->addSql('CREATE INDEX idx_work_rating_source_value ON work_ratings USING btree (source, rating DESC)');

        $this->addSql('CREATE INDEX idx_work_rating_work ON work_ratings USING btree (work_id)');

        $this->addSql('CREATE INDEX idx_work_release_date ON works USING btree (release_date)');

        $this->addSql('CREATE INDEX idx_work_search_vector ON works USING gin (search_vector)');

        $this->addSql('CREATE INDEX idx_work_title_trgm ON works USING gin (title gin_trgm_ops)');

        $this->addSql('CREATE INDEX idx_work_type_added ON works USING btree (type, added_at)');

        $this->addSql('CREATE INDEX idx_work_type_score ON works USING btree (type, external_score DESC NULLS LAST)');

        $this->addSql('CREATE INDEX idx_work_year ON works USING btree (year)');

        $this->addSql('CREATE UNIQUE INDEX uniq_access_token ON access_tokens USING btree (token) WHERE (deleted_at IS NULL)');

        $this->addSql('CREATE UNIQUE INDEX uniq_credit_work_person_role_character ON credits USING btree (work_id, person_id, role, character_name)');

        $this->addSql('CREATE UNIQUE INDEX uniq_entry_user_work ON entries USING btree (user_id, work_id)');

        $this->addSql('CREATE UNIQUE INDEX uniq_episode_season_number ON episodes USING btree (season_id, number)');

        $this->addSql('CREATE UNIQUE INDEX uniq_external_id ON external_ids USING btree (source, external_id)');

        $this->addSql('CREATE UNIQUE INDEX uniq_follow_pair ON follows USING btree (follower_id, followed_id)');

        $this->addSql('CREATE UNIQUE INDEX uniq_genre_slug ON genres USING btree (slug)');

        $this->addSql('CREATE UNIQUE INDEX uniq_person_slug ON people USING btree (slug)');

        $this->addSql('CREATE UNIQUE INDEX uniq_refresh_token ON access_tokens USING btree (refresh_token) WHERE (deleted_at IS NULL)');

        $this->addSql('CREATE UNIQUE INDEX uniq_review_user_work ON reviews USING btree (user_id, work_id)');

        $this->addSql('CREATE UNIQUE INDEX uniq_season_work_number ON seasons USING btree (work_id, number)');

        $this->addSql('CREATE UNIQUE INDEX uniq_seen_mark_user_work ON seen_marks USING btree (user_id, work_id)');

        $this->addSql('CREATE UNIQUE INDEX uniq_user_username ON users USING btree (username) WHERE (deleted_at IS NULL)');

        $this->addSql('CREATE UNIQUE INDEX uniq_work_rating_source ON work_ratings USING btree (work_id, source)');

        $this->addSql('CREATE UNIQUE INDEX uniq_work_type_slug ON works USING btree (type, slug)');

        $this->addSql('CREATE TRIGGER work_ratings_primary_score AFTER INSERT OR DELETE OR UPDATE ON work_ratings FOR EACH ROW EXECUTE FUNCTION refresh_work_primary_score()');

        $this->addSql('ALTER TABLE ONLY credits
    ADD CONSTRAINT credits_person_id_fkey FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY credits
    ADD CONSTRAINT credits_work_id_fkey FOREIGN KEY (work_id) REFERENCES works(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY external_ids
    ADD CONSTRAINT external_ids_work_id_fkey FOREIGN KEY (work_id) REFERENCES works(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY seen_marks
    ADD CONSTRAINT fk_22611e87126f525e FOREIGN KEY (work_id) REFERENCES works(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY seen_marks
    ADD CONSTRAINT fk_22611e87a76ed395 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY entries
    ADD CONSTRAINT fk_2df8b3c5126f525e FOREIGN KEY (work_id) REFERENCES works(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY entries
    ADD CONSTRAINT fk_2df8b3c5a76ed395 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY review_versions
    ADD CONSTRAINT fk_3a9ec9d93e2e969b FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY follows
    ADD CONSTRAINT fk_4b638a73ac24f853 FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY follows
    ADD CONSTRAINT fk_4b638a73d956f010 FOREIGN KEY (followed_id) REFERENCES users(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY access_tokens
    ADD CONSTRAINT fk_58d184bca76ed395 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY reviews
    ADD CONSTRAINT fk_6970eb0f126f525e FOREIGN KEY (work_id) REFERENCES works(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY reviews
    ADD CONSTRAINT fk_6970eb0fa76ed395 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY episodes
    ADD CONSTRAINT fk_7dd55edd4ec001d1 FOREIGN KEY (season_id) REFERENCES seasons(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY seasons
    ADD CONSTRAINT fk_b4f4301c126f525e FOREIGN KEY (work_id) REFERENCES works(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY work_genre
    ADD CONSTRAINT work_genre_genre_id_fkey FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY work_genre
    ADD CONSTRAINT work_genre_work_id_fkey FOREIGN KEY (work_id) REFERENCES works(id) ON DELETE CASCADE');

        $this->addSql('ALTER TABLE ONLY work_ratings
    ADD CONSTRAINT work_ratings_work_id_fkey FOREIGN KEY (work_id) REFERENCES works(id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // A baseline has nothing to step back to: drop the schema and rebuild.
        $this->addSql('DROP SCHEMA public CASCADE');
        $this->addSql('CREATE SCHEMA public');
    }
}
