<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Email on an account, and a way to sign in that is not a password.
 *
 * users.password becomes nullable: an account created through Google has none
 * until its owner sets one.
 *
 * users.email is nullable too, even though sign-up now requires it. Accounts
 * that predate this column exist, and a migration that cannot run against the
 * data already there is a migration that breaks the deploy. Once the addresses
 * are filled in, NOT NULL is a one-line follow-up.
 *
 * Both unique indexes are partial, matching how username already works: a
 * soft-deleted account must not hold its address hostage.
 */
final class Version20260731140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add users.email, optional passwords, and the user_identities table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE users ADD COLUMN email VARCHAR(180) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD COLUMN email_verified BOOLEAN DEFAULT FALSE NOT NULL');
        $this->addSql('ALTER TABLE users ADD COLUMN handle_pending BOOLEAN DEFAULT FALSE NOT NULL');
        $this->addSql('ALTER TABLE users ALTER COLUMN password DROP NOT NULL');

        $this->addSql(
            'CREATE UNIQUE INDEX uniq_user_email ON users (email) WHERE (deleted_at IS NULL AND email IS NOT NULL)'
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE user_identities (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                provider VARCHAR(32) NOT NULL,
                provider_id VARCHAR(191) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);

        $this->addSql(
            'CREATE UNIQUE INDEX uniq_identity_provider_subject ON user_identities (provider, provider_id)'
        );
        $this->addSql('CREATE INDEX idx_identity_user ON user_identities (user_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE user_identities
                ADD CONSTRAINT fk_identity_user FOREIGN KEY (user_id)
                REFERENCES users (id) ON DELETE CASCADE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_identities');
        $this->addSql('DROP INDEX uniq_user_email');
        $this->addSql('ALTER TABLE users DROP COLUMN handle_pending');
        $this->addSql('ALTER TABLE users DROP COLUMN email_verified');
        $this->addSql('ALTER TABLE users DROP COLUMN email');
        // Left nullable: rows added since may have no password to put back.
    }
}
